//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orangify
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.Playlists = new HashSet<Playlist>();
        }
    
        public int Id { get; set; }
        public int ArtistId { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> YearReleased { get; set; }
        public Nullable<int> GenreId { get; set; }
        public System.TimeSpan Length { get; set; }
        public byte[] Artwork { get; set; }
        public Nullable<int> CreditsId { get; set; }
        public string Awards { get; set; }
        public string VideoUrl { get; set; }
        public Nullable<int> LabelId { get; set; }
        public string songPath { get; set; }
    
        public virtual Album Album { get; set; }
        public virtual Artist Artist { get; set; }
        public virtual Credit Credit { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Label Label { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Playlist> Playlists { get; set; }
    }
}
